/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vosb;

//import package
import java.io.FileNotFoundException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Daniel123
 */
public class Window extends javax.swing.JFrame {

    //Fileds
    private VOSB plot; //used to run the story plots
    private List<String> current;

    /**
     * Creates new form Window
     */
    public Window() throws FileNotFoundException {
        initComponents();
        this.plot = new VOSB();
        this.current = new ArrayList<String>();
        this.current.add(this.plot.STARTING_PIC);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        nextBtn = new javax.swing.JButton();
        mainL = new javax.swing.JLabel();
        ABtn = new javax.swing.JButton();
        BBtn = new javax.swing.JButton();
        describingL = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        mainL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalRecreation/VOSB_00.jpg"))); // NOI18N

        ABtn.setText("Do something else");
        ABtn.setToolTipText("");
        ABtn.setEnabled(false);
        ABtn.setMaximumSize(new java.awt.Dimension(127, 27));
        ABtn.setMinimumSize(new java.awt.Dimension(127, 27));
        ABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABtnActionPerformed(evt);
            }
        });

        BBtn.setText("Believe in God!!");
        BBtn.setEnabled(false);
        BBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBtnActionPerformed(evt);
            }
        });

        describingL.setFont(new java.awt.Font("Bradley Hand ITC", 0, 24)); // NOI18N
        describingL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        describingL.setText("<html><p>Let us explore how Brendan made himself a hero by his persistence faith in God!!</p></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(describingL, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainL, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(ABtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(BBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(describingL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainL, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        //set the icon to be the preceeding scene
        this.mainL.setIcon(new ImageIcon(this.getClass().getResource(this.plot.PARENT_DIR + this.current.get(0))));
        //change the text to the corresponding scene
        this.describingL.setText(this.plot.getDiscrip(this.current.get(0)));
        //switch to the next scene
        this.current = this.plot.getNextPic(this.current.get(0));
        if(this.current.size() != 1){
            //make the options enabled and nextBut disabled
            this.ABtn.setEnabled(true);
            this.BBtn.setEnabled(true);
            this.nextBtn.setEnabled(false);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

       //if the user choosed to do something else.......
    private void ABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABtnActionPerformed
        //set the icon as the user choosed
        this.mainL.setIcon(new ImageIcon(this.getClass().getResource(this.plot.PARENT_DIR + this.current.get(0))));
        //make the discription correspond to the scene
        this.describingL.setText(this.plot.getDiscrip(this.current.get(0)));
        //switch to the next scene
        this.current = this.plot.getNextPic(this.current.get(0));
        //put everything back to original status
        this.ABtn.setEnabled(false);
        this.BBtn.setEnabled(false);
        this.nextBtn.setEnabled(true);
    }//GEN-LAST:event_ABtnActionPerformed

    //if the user choose to believe in God
    private void BBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBtnActionPerformed
        //set the icon as the user choosed
        this.mainL.setIcon(new ImageIcon(this.getClass().getResource(this.plot.PARENT_DIR + this.current.get(1))));
        //make the discription correspond to the scene
        this.describingL.setText(this.plot.getDiscrip(this.current.get(1)));
        //switch to the next scene
        this.current = this.plot.getNextPic(this.current.get(1));
        //put everything back to original status
        this.ABtn.setEnabled(false);
        this.BBtn.setEnabled(false);
        this.nextBtn.setEnabled(true);
    }//GEN-LAST:event_BBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new Window().setVisible(true);
                }catch(Exception e){
                    System.out.println(e.toString());
                }
            }
        }) ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABtn;
    private javax.swing.JButton BBtn;
    private javax.swing.JLabel describingL;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel mainL;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
